### ISSUE TITLE
Uncaught SyntaxError: Unexpected token $ in JSON at position 0

### ISSUE THREAD

**Issue by PaulFrost** [James-Yu/Atom-LaTeX#147]
[Enter steps to reproduce:]

1. Build
2. CMD + Left click in tikzpicture environment

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.4

### Stack Trace

Uncaught SyntaxError: Unexpected token $ in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token $ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Viewer.module.exports.Viewer.wsHandler (/packages/atom-latex/lib/viewer.coffee:18:17)
    at /packages/atom-latex/lib/server.coffee:23:47)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/packages/atom-latex/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/atom-latex/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/atom-latex/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/atom-latex/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:138:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:560:20)
```

### Commands

```
     -1:58.3.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
 14x -1:51.8.0 core:move-down (input.hidden-input)
     -1:49.5.0 editor:consolidate-selections (input.hidden-input)
     -1:49.5.0 core:cancel (input.hidden-input)
     -1:34.8.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
     -1:31.6.0 application:add-project-folder (ol.tree-view-root.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:10.7.0 atom-latex:build (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.4 
```

**Comment by ashthespy** [comment]
Hi, closing this issue, can we continue debugging at #139
