### ISSUE TITLE
Uncaught TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function

### ISSUE THREAD

**Issue by phemps** [James-Yu/Atom-LaTeX#153]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.4

### Stack Trace

Uncaught TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function

```
At /Users/dan_lab7/.atom/packages/atom-latex/lib/viewer.coffee:40

TypeError: atom.workspace.paneForItem(...).activeItem.updateTitle is not a function
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:40:55)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:122:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:76:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:34 editor:move-to-first-character-of-line (input.hidden-input)
     -2:33 core:move-left (input.hidden-input)
     -2:31.2.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:30.7.0 core:move-left (input.hidden-input)
  9x -2:30.4.0 core:move-right (input.hidden-input)
     -2:28.9.0 editor:select-to-first-character-of-line (input.hidden-input)
     -2:28.1.0 core:backspace (input.hidden-input)
  2x -2:03.2.0 editor:newline (input.hidden-input)
     -1:59.3.0 autocomplete-plus:confirm (input.hidden-input)
  5x -1:58.4.0 core:backspace (input.hidden-input)
     -1:57.3.0 core:save (input.hidden-input)
     -0:37.4.0 find-and-replace:show (input.hidden-input)
  2x -0:36.8.0 core:backspace (input.hidden-input)
     -0:33.9.0 core:confirm (input.hidden-input)
     -0:26.7.0 core:backspace (input.hidden-input)
     -0:07.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-latex 0.8.4 
git-control 0.9.0 
git-projects 1.17.0 
git-time-machine 1.5.9 
latex 0.50.0 
scroll-through-time 0.3.0 
teletype 0.13.2 
```

**Comment by ashthespy** [comment]
Closing for now - please feel free to reopen with steps to reproduce.
