### ISSUE TITLE
Uncaught TypeError: Class constructor Disposable cannot be invoked without 'new'

### ISSUE THREAD

**Issue by MichaelLLink** [James-Yu/Atom-LaTeX#179]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.0-beta3 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.5

### Stack Trace

Uncaught TypeError: Class constructor Disposable cannot be invoked without 'new'

```
At /Users/michaellink/.atom/packages/atom-latex/lib/view/panel.js:8

TypeError: Class constructor Disposable cannot be invoked without 'new'
    at /packages/atom-latex/lib/view/panel.js:8:27)
    at /packages/atom-latex/lib/main.coffee:114:14)
    at Object.lazyLoad (/packages/atom-latex/lib/main.coffee:23:14)
    at /packages/atom-latex/lib/main.coffee:16:30
```

### Commands

```
     -1:04.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -0:49.4.0 fuzzy-finder:toggle-buffer-finder (ul.list-inline.tab-bar.inset-panel)
     -0:39.5.0 atom-latex:build (ul.list-inline.tab-bar.inset-panel)
     -0:30.8.0 atom-latex:preview-tab (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-latex 0.8.5 
latex 0.50.0 
latex-image-paste 0.3.1 
latextools 0.8.5 
```

**Comment by larp-welt** [comment]
Same to me!

```
TypeError: Class constructor Disposable cannot be invoked without 'new'
    at new Panel (/home/tiggr/.atom/packages/atom-latex/lib/view/panel.js:8:27)
    at new AtomLaTeX (/home/tiggr/.atom/packages/atom-latex/lib/main.coffee:114:14)
    at Object.lazyLoad (/home/tiggr/.atom/packages/atom-latex/lib/main.coffee:23:14)
    at /home/tiggr/.atom/packages/atom-latex/lib/main.coffee:16:30
```

```
Atom    : 1.32.0-beta3
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3
```

on

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic
```

**Comment by ashthespy** [comment]
@MichaelLLink does that solve your issue as well? I don't have time to test with a beta release right now.

**Comment by ashthespy** [comment]
https://github.com/atom/event-kit/pull/44 fixed this.
