### ISSUE TITLE
Uncaught SyntaxError: Unexpected token K in JSON at position 0

### ISSUE THREAD

**Issue by samfdwang** [James-Yu/Atom-LaTeX#207]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Linux Mint
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.7

### Stack Trace

Uncaught SyntaxError: Unexpected token K in JSON at position 0

```
At file:///usr/share/atom/resources/app.asar/static/index.html:1

SyntaxError: Unexpected token K in JSON at position 0
    at JSON.parse (<anonymous>)
    at Viewer.module.exports.Viewer.wsHandler (/packages/atom-latex/lib/viewer.coffee:18:17)
    at /packages/atom-latex/lib/server.coffee:23:47)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:141:47)
    at Receiver.dataMessage (/packages/atom-latex/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/packages/atom-latex/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/packages/atom-latex/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/packages/atom-latex/node_modules/ws/lib/Receiver.js:139:10)
    at Socket._ultron.on (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:138:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -2:52.5.0 atom-latex:build (input.hidden-input)
     -2:09.4.0 atom-latex:preview-tab (input.hidden-input)
     -0:51.9.0 core:move-right (input.hidden-input)
     -0:44.9.0 command-palette:toggle (input.hidden-input)
  7x -0:38.4.0 core:move-down (input.hidden-input)
 16x -0:32.4.0 core:move-up (input.hidden-input)
  3x -0:24.3.0 core:move-down (input.hidden-input)
     -0:20.5.0 core:confirm (input.hidden-input)
     -0:20.5.0 atom-latex:preview (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.8.7 
latex 0.50.2 
```

**Comment by ashthespy** [comment]
This was an artefact of #206 and should be fixed with `v0.8.8`
