### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by scheuclu** [James-Yu/Atom-LaTeX#28]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.1
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.2

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /home/lukas/.atom/packages/atom-latex/lib/locator.coffee:62

TypeError: Cannot read property 'replace' of undefined
    at /packages/atom-latex/lib/locator.coffee:62:42
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-ctags 5.0.0 
atom-latex 0.7.2 
autocomplete-clang 0.10.0 
ctags-status 1.3.7 
git-plus 7.3.3 
language-cpp14 0.6.2 
language-latex 1.0.0 
latex-plus 0.9.1 
latexer 0.3.0 
linter 1.11.23 
linter-chktex 1.3.0 
minimap 4.26.8 
pdf-view 0.56.0 
symbols-tree-view 0.13.2 
Zen 0.16.4 
```

**Comment by James-Yu** [comment]
Please provide more information on the issue.
