### ISSUE TITLE
Uncaught TypeError: path must be a string or Buffer

### ISSUE THREAD

**Issue by antoniopugliese** [James-Yu/Atom-LaTeX#45]
This happens when trying to save a file.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.5

### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At C:\Users\Antonio\AppData\Local\atom\app-1.15.0\resources\app.asar\src\pane.js:1045

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Manager.module.exports.Manager.loadLocalCfg (/packages/atom-latex/lib/manager.coffee:16:5)
    at Manager.module.exports.Manager.isTexFile (/packages/atom-latex/lib/manager.coffee:29:20)
    at /packages/atom-latex/lib/main.coffee:50:29
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextBuffer.module.exports.TextBuffer.save (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1048:19)
    at TextEditor.module.exports.TextEditor.save (/app.asar/src/text-editor.js:915:26)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:753:18)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -3:42 atom-latex:toggle-panel (input.hidden-input)
  2x -3:32.5.0 atom-latex:build-here (input.hidden-input)
     -2:53.4.0 autocomplete-plus:activate (input.hidden-input)
  2x -2:52.8.0 core:save (input.hidden-input)
     -2:46.8.0 atom-latex:toggle-panel (input.hidden-input)
  2x -2:23.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.5 
highlight-selected 0.13.1 
minimap 4.27.1 
minimap-highlight-selected 4.6.1 
script 3.14.1 
```

**Comment by ashthespy** [comment]
Hi! 
Can you share more information with regards to your `.latexcfg`?
Also general information if it was a standard `.tex` file or something else?

Cheers!

**Comment by James-Yu** [comment]
@antoniopugliese It seems your magic comment and/or `.latexfg` point to an invalid file path. Can you please confirm?

**Comment by antoniopugliese** [comment]
Found the problem. I had opened another file from a different folder, and therefore atom was looking at the wrong directory as the project directory.

I don't know if you want to consider this an issue. For what I can see you can resolve this one.

Thanks for the prompt support!

**Comment by James-Yu** [comment]
Will look into that later

**Comment by ashthespy** [comment]
This is a byproduct of #31 and the related commits. We need to think of a solution that works for both use cases!
As part of #47 - I [have implemented a first backup](https://github.com/James-Yu/Atom-LaTeX/pull/47/files#diff-c9b4f199851474c585bd505761e0123dR8) - but it's rather rudimentary and crude! 
Ideally the config shouldn't be loaded if the current file is not a valid LaTeX file - but that becomes a chicken and egg issue when it comes to custom file formats! 

@antoniopugliese  Could I ask what type of file was open when you called the build command? Just to understand other types of workflow :-)

**Comment by carnage101** [comment]
Hi. I've followed the guide on the package page to define the root file but i'm still unable to build my master .tex document. I get this error report. I should probably mention my master file is a book and it calls all the chapters (which include .pdf graphics and tabels) stored in separate .tex files through latex `\include` or `\input` commands. Does atom require a specific setup to build a latex document like this? 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.12


### Stack Trace

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:951

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Manager.module.exports.Manager.loadLocalCfg (/packages/atom-latex/lib/manager.coffee:33:5)
    at Manager.module.exports.Manager.isTexFile (/packages/atom-latex/lib/manager.coffee:46:20)
    at Manager.module.exports.Manager.findMainSelfMagic (/packages/atom-latex/lib/manager.coffee:103:11)
    at Manager.module.exports.Manager.findMainSequence (/packages/atom-latex/lib/manager.coffee:68:23)
    at Manager.module.exports.Manager.findMain (/packages/atom-latex/lib/manager.coffee:53:15)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:12:24)
    at /packages/atom-latex/lib/main.coffee:34:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.18.0/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.18.0/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -2:31.1.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -2:25.2.0 core:backspace (input.hidden-input)
  2x -2:23.3.0 core:confirm (input.hidden-input)
     -2:19 find-and-replace:focus-next (input.hidden-input)
     -2:18.5.0 find-and-replace:focus-previous (input.hidden-input)
     -2:17.3.0 core:select-all (input.hidden-input)
     -2:14.4.0 core:backspace (input.hidden-input)
     -2:12.4.0 core:confirm (input.hidden-input)
     -2:07.8.0 core:select-all (input.hidden-input)
     -2:06.6.0 core:confirm (input.hidden-input)
     -2:00.5.0 editor:consolidate-selections (input.hidden-input)
     -2:00.5.0 core:cancel (input.hidden-input)
     -0:15.8.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
     -0:14.6.0 editor:consolidate-selections (input.hidden-input)
     -0:14.6.0 core:cancel (input.hidden-input)
     -0:13.2.0 atom-latex:build-here (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.12 
```
