### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by deadda7a** [James-Yu/Atom-LaTeX#59]
Hi,
I just stumbled over the error mentioned above.
If you need any more information just let me know! I am using XeTex instead of pdfTeX.

All the best

Steps to reproduec:
1. Open a .tex file
2. Click on "Build LaTeX"

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: "Fedora release 25 with kernel 4.10.11-200.fc25.x86_64
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.7
**TeX** in Version 3.14159265 (TeX Live 2016)
**XeTeX** in Version 3.14159265-2.6-0.99996 (TeX Live 2016)

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /usr/share/atom/resources/app.asar/src/pane.js:847

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/app.asar/src/pane.js:847:15)
    at Pane.module.exports.Pane.focus (/app.asar/src/pane.js:252:21)
    at Viewer.module.exports.Viewer.focusMain (/packages/atom-latex/lib/viewer.coffee:54:11)
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:48:21)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:96:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:42:8)
    at /packages/atom-latex/lib/builder.coffee:58:12
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:34.2.0 core:paste (input.hidden-input)
  3x -6:33.6.0 core:move-right (input.hidden-input)
  2x -6:33 core:backspace (input.hidden-input)
     -6:31.8.0 core:move-right (input.hidden-input)
     -6:30.8.0 core:move-left (input.hidden-input)
  3x -6:29.9.0 core:backspace (input.hidden-input)
  2x -6:26.4.0 core:move-down (input.hidden-input)
     -6:26 core:move-left (input.hidden-input)
  7x -6:25.7.0 core:select-left (input.hidden-input)
     -6:24.3.0 core:paste (input.hidden-input)
     -6:23.3.0 core:backspace (input.hidden-input)
     -6:22.9.0 core:save (input.hidden-input)
     -0:31.7.0 core:backspace (input.hidden-input)
     -0:27.4.0 core:copy (input.hidden-input)
     -0:26.4.0 core:paste (input.hidden-input)
     -0:25.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-latex 0.7.7 
code-stats-atom 2.0.1 
```

**Comment by ashthespy** [comment]
Could you confirm what you have for the following settings:
1. `Focus PDF viewer window after building`
1. `Preview PDF after building`

**Comment by deadda7a** [comment]
Yes; Here is the custom configuration I set, all beside that is default:

`"atom-latex":
    bibtex: "/usr/bin/true"
    compiler: "xelatex"
    hide_log_if_success: true
    preview_after_build: "View in PDF viewer tab"
    toolchain: "custom toolchain"`

**Comment by ashthespy** [comment]
Thanks for that, I can now reproduce the error with:

1. Open `.tex' file 
1. Click on "Build LaTeX" -> new split right PDF Viewer tab is created 
1. Drag the `.tex` file's editor pane to the right to collapse the split panes
1. Click on "Build LaTeX"
