### ISSUE TITLE
Uncaught "Invalid child node" error

### ISSUE THREAD

**Issue by wiiareonfire** [James-Yu/Atom-LaTeX#62]
Hey, I just updated to atom-latex v0.7.7, and I'm getting an uncaught error from incompatible-packages. Disabling atom-latex prevents the error, but I can't use atom-latex either way. 

A bit of reading suggests that this (atom/incompatible-packages/issues/21) might be related? 

Here's the error report

**Atom**: 1.17.0-beta4 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [incompatible-packages](https://github.com/atom/incompatible-packages) package 0.27.2

### Stack Trace

Uncaught Error: Invalid child node: undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/dom.js:25

Error: Invalid child node: undefined
    at Object.dom (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/dom.js:25:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/incompatible-packages/lib/incompatible-packages-component.js:207:1
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatibleModules (/Applications/Atom.app/Contents/Resources/app/node_modules/incompatible-packages/lib/incompatible-packages-component.js:203:1)
    at IncompatiblePackagesComponent.renderIncompatiblePackage (/Applications/Atom.app/Contents/Resources/app/node_modules/incompatible-packages/lib/incompatible-packages-component.js:156:1)
    at Array.map (native)
    at IncompatiblePackagesComponent.renderIncompatiblePackageList (/Applications/Atom.app/Contents/Resources/app/node_modules/incompatible-packages/lib/incompatible-packages-component.js:132:1)
    at IncompatiblePackagesComponent.render (/Applications/Atom.app/Contents/Resources/app/node_modules/incompatible-packages/lib/incompatible-packages-component.js:83:1)
    at updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:99:1)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:72:1
    at DefaultScheduler.performUpdates (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/default-scheduler.js:48:1)
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.7.7 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.10 
atom-terminal 0.8.0 
autocomplete-java 1.2.5 
busy-signal 1.4.1 
docblockr 0.9.4 
file-icons 2.1.4 
fonts 2.0.0 
git-status 0.3.4 
gpp-compiler 3.0.7 
intentions 1.1.2 
language-latex 1.0.0 
linter 2.1.4 
linter-chktex 1.3.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-python 3.1.1 
linter-shellcheck 1.4.4 
linter-ui-default 1.2.3 
linter-write-good 0.9.0 
make-runner 1.1.15 
pdf-view 0.57.0 
project-manager 3.3.4 
tree-view-git-branch 0.1.2 
```

**Comment by ashthespy** [comment]
Hi, this seems to be an upstream issue with the Atom 1.17 beta that you are on.
The issue should  be fixed https://github.com/atom/incompatible-packages/commit/77623c35e6bee47441067f210876540e4cca19c8 
Try upgrading to the latest with `apm install incompatible-packages@0.27.3`

Closing the issue, but let us know if it still persists!
