### ISSUE TITLE
Attempting to save or build a tex file on Mac OS fails due to incorrect path

### ISSUE THREAD

**Issue by mlangiu** [James-Yu/Atom-LaTeX#64]
One thing that might be of importance is that the OS and data/atom files are on different partitions:
(``/Volumes/Macintosh\ HD`` vs. ``/Volumes/DATA/<user>/.atom``).

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.6

### Stack Trace building

Uncaught TypeError: path must be a string or Buffer

```
At fs.js:951

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Manager.module.exports.Manager.loadLocalCfg (/packages/atom-latex/lib/manager.coffee:22:5)
    at Builder.module.exports.Builder.setCmds (/packages/atom-latex/lib/builder.coffee:113:20)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:16:6)
    at HTMLElement.click (/packages/atom-latex/lib/view/panel.js:106:85)
```

### Commands building

```
  4x -1:34.2.0 latex:build (input.hidden-input)
```

### Stack Trace saving

Uncaught TypeError: path must be a string or Buffer

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

TypeError: path must be a string or Buffer
    at TypeError (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:571:28)
    at Manager.module.exports.Manager.loadLocalCfg (/packages/atom-latex/lib/manager.coffee:22:5)
    at Manager.module.exports.Manager.isTexFile (/packages/atom-latex/lib/manager.coffee:35:20)
    at /packages/atom-latex/lib/main.coffee:50:29
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1082:27)
    at TextEditor.module.exports.TextEditor.saveAs (/app.asar/src/text-editor.js:919:26)
    at Pane.module.exports.Pane.saveItemAs (/app.asar/src/pane.js:781:16)
    at Pane.saveItemAs (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:765:21)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/app.asar/src/workspace.js:693:35)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands saving

```
  6x -6:52.1.0 latex:build (input.hidden-input)
  4x -1:29 core:backspace (input.hidden-input)
  4x -1:25.8.0 latex:build (input.hidden-input)
     -1:02.6.0 application:new-file (input.hidden-input)
 14x -0:54.2.0 core:backspace (input.hidden-input)
     -0:52.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.6 
language-gams 0.2.0 
language-modelica 0.5.0 
```

**Comment by ashthespy** [comment]
Question time! ( really need to setup some debugging logs!)

1. Do you have multiple Atom projects open when this occurs?
1. Are you building via the `Package` → `Atom-LaTeX` → `Build LaTeX` or the `Build LaTeX` from the bottom panel?

If so, I believe I know the source of the error, and will work on a more robust handling of multiple latex projects. 
Currently, it only works by checking setting the LaTeX root dir from the current active text editor.

**Comment by mlangiu** [comment]
Answer time!

1. Nope, just a basic MWE:
```
\documentclass{article}
\begin{document}
 Test
\end{document}
```
2. Both lead to the abovementioned error.

**Comment by ashthespy** [comment]
Few more tests :-)
1. Could you open the developer console (<kbd>ctrl</kbd>+<kbd>shift</kbd> +<kbd>i</kbd>) and enter `atom.project.getPaths()` and post results?
1. Does building via keyboard binding (<kbd>ctrl</kbd>+<kbd>L</kbd> <kbd>ctrl</kbd>+<kbd>B</kbd>) work?

**Comment by mlangiu** [comment]
Ok you got me ;) 
It was a noob error: 
I was still residing in the project path of a previous project and wasn't aware that you manually need to add the project folder containing the required document before being able to build.
After doing that all works as expected.

One change I suggest is to try adding support for this scenario:

1.  Noob installs Atom and Atom-LaTeX.
2. Noob creates a tex file from scratch and wants to save it.
3. Atom-LaTeX recognizes that no corresponding Atom project has been created and hence the required path variable is not set.
4. Prompt noob whether he wants to set up the new project or save in one that is already open instead of throwing the above error.

Cheers and thanks for the support.

**Comment by ashthespy** [comment]
Glad to know it's sorted, and thanks for the feedback!

For future reference, when creating just a stand alone new `.tex` file, you could build it with the `Build LaTeX from active editor` command. 

Normally, the plugin gives the user quite a detailed warning prompt when no root `.tex` file is found to build. That being said, the issue you faced stems from how Atom-LaTeX currently tries to find if a custom `.latexcfg` is set prior to that. So you never got to that prompt!

This is a bit an interesting scenario, given how Atom manages open projects - but such errors should reduce with #65  and thus giving the user a more expressive prompt rather than these cryptic TypeErrors!
