### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ahmadfiroz** [James-Yu/Atom-LaTeX#66]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.8

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1045

TypeError: Cannot read property 'match' of undefined
    at Parser.module.exports.Parser.parse (/packages/atom-latex/lib/parser.coffee:23:11)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:85:19)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:42:8)
    at Builder.module.exports.Builder.build (/packages/atom-latex/lib/builder.coffee:24:6)
    at /packages/atom-latex/lib/main.coffee:51:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/app.asar/node_modules/text-buffer/lib/text-buffer.js:1092:27)
    at TextEditor.module.exports.TextEditor.saveAs (/app.asar/src/text-editor.js:924:26)
    at Pane.module.exports.Pane.saveItemAs (/app.asar/src/pane.js:781:16)
    at Pane.saveItemAs (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItem (/app.asar/src/pane.js:765:21)
    at Pane.saveItem (/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/app.asar/src/pane.js:736:19)
    at Workspace.saveActivePaneItem (/app.asar/src/workspace.js:851:33)
    at /app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -7:15.2.0 editor:newline (input.hidden-input)
     -7:12.3.0 autocomplete-plus:confirm (input.hidden-input)
  7x -7:06.5.0 core:backspace (input.hidden-input)
     -3:51.8.0 core:move-down (input.hidden-input)
  2x -3:51.5.0 editor:newline (input.hidden-input)
  2x -3:49.9.0 core:move-up (input.hidden-input)
     -3:42.8.0 autocomplete-plus:confirm (input.hidden-input)
 10x -3:31.1.0 core:backspace (input.hidden-input)
     -3:09.7.0 core:select-all (input.hidden-input)
  4x -3:02.8.0 core:copy (input.hidden-input)
     -2:55.4.0 tree-view:toggle (input.hidden-input)
  2x -2:52.8.0 tree-view:copy (ol.tree-view.list-tree.has-collapsable-children.focusable-panel.full-menu)
     -2:43.9.0 git-plus:add (input.hidden-input)
     -2:43.9.0 core:save-as (input.hidden-input)
     -2:40.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.8 
atom-material-syntax-dark 0.2.7 
atom-material-ui 1.3.10 
autocomplete-clang 0.11.3 
build 0.67.0 
busy 0.7.0 
busy-signal 1.4.1 
dictionary 0.5.0 
emmet 2.4.3 
file-icons 2.1.4 
git-plus 7.7.0 
gitignore-snippets 0.2.5 
intentions 1.1.2 
language-gitignore 0.3.0 
language-ini 1.19.0 
language-latex 1.0.0 
linter 2.1.4 
linter-chktex 1.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.2.3 
minimap 4.28.1 
pandoc-convert 1.1.0 
pdf-view 0.57.0 
platformio-ide 2.0.0-beta.2 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
tool-bar 1.1.0 
wordcount 2.10.4 
Zen 0.16.4 
```

**Comment by ashthespy** [comment]
HI,
Could you elaborate on the steps to reproduce this issue?

**Comment by ahmadfiroz** [comment]
Just bulding produces the issue. Package>Atom-Latex>Build Latex

**Comment by ashthespy** [comment]
Looking at the stack trace, it would seem that your Atom-LaTeX did not find a defined toolchain to use. 
Could you give me the following information.
1. Your toolchain settings
2. Entries for atom-latex configuration from `config.cson` (found from the menu File -> Config..)

**Comment by ahmadfiroz** [comment]
Resolved. the toolchain setup auto makes the problem. if I define it to latexmk then the problem doesn't appear.  I think the auto option should be removed. Anyway closing the issue

**Comment by ashthespy** [comment]
The auto toolchain by default first tries `latexmk` and then if that fails tires the `custom` toolchain. 

Thanks for the feedback, will try investigating further later.
