### ISSUE TITLE
Uncaught Error: Could not call remote function 'getTitle'. Check that the function signature is c...

### ISSUE THREAD

**Issue by SureshRaja1** [James-Yu/Atom-LaTeX#68]
[Enter steps to reproduce:]

1. Click on open PDF in tab
2. Compile latex
3. Received the error messages below

It appears that you cannot run the PDF view in tab mode.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.8

### Stack Trace

Uncaught Error: Could not call remote function 'getTitle'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getTitle'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (C:\Users\Suresh\AppData\Local\atom\app-1.16.0\resources\electron.asar\browser\rpc-server.js:226:11)
    at EventEmitter.<anonymous> (C:\Users\Suresh\AppData\Local\atom\app-1.16.0\resources\electron.asar\browser\rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Suresh\AppData\Local\atom\app-1.16.0\resources\electron.asar\browser\api\web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
At C:\Users\Suresh\AppData\Local\atom\app-1.16.0\resources\electron.asar\renderer\api\remote.js:210

Error: Could not call remote function 'getTitle'. Check that the function signature is correct. Underlying error: Object has been destroyed
Error: Could not call remote function 'getTitle'. Check that the function signature is correct. Underlying error: Object has been destroyed
    at callFunction (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/browser/rpc-server.js:226:11)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/browser/rpc-server.js:307:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/browser/api/web-contents.js:222:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/renderer/api/remote.js:210:13)
    at undefined.remoteMemberFunction (~/AppData/Local/atom/app-1.16.0/resources/electron.asar/renderer/api/remote.js:111:18)
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:42:34)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:96:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:42:8)
    at /packages/atom-latex/lib/builder.coffee:58:12
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -9:42.1.0 fuzzy-finder:toggle-buffer-finder (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -5:52.3.0 intentions:highlight (input.hidden-input)
     -5:51.9.0 find-and-replace:show (input.hidden-input)
 12x -5:49.6.0 core:move-left (input.hidden-input)
     -5:48.2.0 core:delete (input.hidden-input)
  2x -5:44.4.0 core:backspace (input.hidden-input)
     -5:15 editor:consolidate-selections (input.hidden-input)
     -5:15 core:cancel (input.hidden-input)
  2x -3:14.9.0 auto-indent:apply (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:49.5.0 core:backspace (input.hidden-input)
     -2:47.9.0 intentions:highlight (input.hidden-input)
     -2:47.6.0 core:save (input.hidden-input)
     -0:30.5.0 atom-latex:preview-tab (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-latex 0.7.8 
auto-indent 0.5.0 
autocomplete-python 1.8.63 
busy-signal 1.4.1 
file-icons 2.1.4 
Hydrogen undefined 
hydrogen-launcher 1.2.1 
intentions 1.1.2 
kite 0.22.0 
language-latex 1.0.0 
latex 0.43.0 
latex-completions 0.3.2 
linter 2.1.4 
linter-flake8 2.2.1 
linter-ui-default 1.2.4 
minimap 4.28.2 
my-package 0.0.0 
pdf-view 0.57.0 
platformio-ide-terminal 2.5.0 
python-autopep8 0.1.3 
r-exec 0.5.0 
script 3.14.1 
set-syntax 0.3.2 
```

**Comment by ashthespy** [comment]
Stumbled up this as well - it arises in an interesting sequence of events:
1. `Preview PDF after building process` setting is set to `View in PDF viewer tab`
1. PDF Viewer window is created ( `Package`→`Atom-LaTeX`→`Preivew PDF`)
1. PDF Viewer window is closed.
1. Action is toggled to create a new PDF Viewer tab (Buid/Preview)

Now any more actions (Build/Preview) on the same file will throw this error. 

Will find a solution :-)
