### ISSUE TITLE
Failed to load the atom-latex package

### ISSUE THREAD

**Issue by NOPtex** [James-Yu/Atom-LaTeX#79]
Hi i can't use the plugin after updating.
I get:

Unexpected token } in JSON at position 11360 in 

    /Users/<user>/.atom/packages/atom-latex/package.json

Stacktrace:

`
    SyntaxError: Unexpected token } in JSON at position 11360
        at Object.parse (native)
        at parseObject (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:58:25)
        at parseContentsSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:72:22)
        at Object.readFileSync (/Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:174:20)
        at PackageManager.module.exports.PackageManager.loadPackageMetadata (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:825:35)
        at PackageManager.module.exports.PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:530:43)
        at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:479:25
        at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:321:22)
        at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:473:25)
        at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:812:34
      at /Users/<user>/.atom/packages/atom-latex/package.json:1:1
`

**Comment by ashthespy** [comment]
Does your problem still persist? Again, I am unable to recreate the error, and the [`package.json`](https://github.com/James-Yu/Atom-LaTeX/blob/master/package.json) looks fine. 

Could you try reinstalling Atom-LaTeX?

**Comment by ashthespy** [comment]
Closing due to lack of further information - fee free to reopen if required!
