### ISSUE TITLE
Uncaught Error: Replacing non-existent child

### ISSUE THREAD

**Issue by Leithian** [James-Yu/Atom-LaTeX#81]
[Enter steps to reproduce:]

I have no idea, I can't even reproduce it myself. I played around with the file-icons package trying to get some icons in the treeview (which did't work) and then I hit save to build a LaTeX-file.

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.11

### Stack Trace

Uncaught Error: Replacing non-existent child

```
At C:\Users\**\AppData\Local\atom\app-1.19.0-beta3\resources\app\src\pane-container.js:145

Error: Replacing non-existent child
    at PaneContainer.replaceChild (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane-container.js:145:47)
    at Pane.module.exports.Pane.split (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane.js:984:27)
    at Pane.module.exports.Pane.splitRight (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/pane.js:964:25)
    at Viewer.module.exports.Viewer.openViewerNewTab (/packages/atom-latex/lib/viewer.coffee:120:38)
    at Viewer.module.exports.Viewer.openViewer (/packages/atom-latex/lib/viewer.coffee:73:8)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:104:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:47:8)
    at /packages/atom-latex/lib/builder.coffee:63:12
    at ChildProcess.exithandler (child_process.js:214:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

### Commands

```
     -1:21.1.0 core:confirm (input.hidden-input)
     -0:33.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-latex 0.7.11 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-python 1.9.1 
dash-ui 0.4.0 
file-icons 2.1.8 
file-type-icons 1.3.4 
glowing-cursor 0.1.2 
highlight-selected 0.13.1 
language-latex 1.0.0 
latex 0.44.0 
latexer 0.3.0 
material-ui 1.0.10 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.1 
minimap-selection 4.4.0 
neon-selection 0.3.2 
pdf-view 0.59.0 
script 3.15.0 
```

**Comment by ashthespy** [comment]
Seems to be an upstream error (https://github.com/atom/tree-view/issues/1096)
