### ISSUE TITLE
Uncaught TypeError: Cannot read property '6' of undefined

### ISSUE THREAD

**Issue by Leithian** [James-Yu/Atom-LaTeX#82]
[Enter steps to reproduce:]
1. type `\begin{figure}`

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.11

### Stack Trace

Uncaught TypeError: Cannot read property '6' of undefined

```
At C:\Users\D067862\.atom\packages\atom-latex\lib\provider.coffee:48

TypeError: Cannot read property '6' of undefined
    at Object.onDidInsertSuggestion (/packages/atom-latex/lib/provider.coffee:48:42)
    at AutocompleteManager.confirm (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:594:37)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:258:22
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirm (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:145:33)
    at SuggestionListElement.confirmSelection (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/autocomplete-plus/lib/suggestion-list-element.js:234:31)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at SuggestionList.confirmSelection (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/autocomplete-plus/lib/suggestion-list.js:150:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta3/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  3x -2:23.4.0 core:backspace (input.hidden-input)
     -2:22.4.0 editor:consolidate-selections (input.hidden-input)
     -2:22.4.0 core:cancel (input.hidden-input)
  3x -2:21.4.0 core:move-down (input.hidden-input)
     -2:20.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:27.7.0 tabs:open-in-new-window (div.title.icon.tex-icon.medium-blue)
     -1:02.0 core:backspace (input.hidden-input)
     -1:01.1.0 core:save (input.hidden-input)
  2x -0:54.4.0 core:delete (input.hidden-input)
     -0:53 core:save (input.hidden-input)
     -0:47.5.0 command-palette:toggle (input.hidden-input)
     -0:46.2.0 core:confirm (input.hidden-input)
     -0:46.2.0 atom-latex:clean (input.hidden-input)
     -0:42 atom-latex:build (input.hidden-input)
     -0:25.7.0 editor:newline (input.hidden-input)
  2x -0:13.8.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.13 
atom-latex 0.7.11 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
autocomplete-python 1.9.1 
file-icons 2.1.8 
glowing-cursor 0.1.2 
highlight-selected 0.13.1 
language-latex 1.0.0 
latex 0.44.0 
latexer 0.3.0 
material-ui 1.0.10 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-plus 4.29.1 
minimap-selection 4.4.0 
neon-selection 0.3.2 
pdf-view 0.59.0 
script 3.15.0 
tablr 1.8.3 
```

**Comment by mortenpi** [comment]
I just ran into a similar bug with the dollar signs. I don't have any experience with atom plugins, but as far as I can tell it is caused by the `editor.buffer.lines` access. Switching that to `editor.getBuffer().getLines()` seems to fix it.
