### ISSUE TITLE
Failed to activate the atom-latex package

### ISSUE THREAD

**Issue by schaeferlea** [James-Yu/Atom-LaTeX#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.11

### Stack Trace

Failed to activate the atom-latex package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:74:19)
    at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/composite-disposable.js:43:17)
    at requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:110:29)
    at Object.requireAutocompleteManagerAsync (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:31:15)
    at Object.consumeProvider (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:107:16)
    at Object.consumeProvider_2_0 (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete-plus/lib/main.js:86:23)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/provider.js:34:58)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/lib/service-hub.js:30:26)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app/src/package.js:446:77)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:256:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -6:06.4.0 core:close (input.hidden-input)
     -6:02.8.0 core:paste (input.hidden-input)
     -6:01.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -6:00.0 core:confirm (input.hidden-input)
     -5:58.4.0 core:save (input.hidden-input)
     -5:36.9.0 core:close (input.hidden-input)
  2x -5:23.4.0 latex-plus:compile-and-sync (div.tool-panel.tree-view)
     -4:34.3.0 latex:build (input.hidden-input)
     -4:26.4.0 settings-view:open (input.hidden-input)
     -3:37.7.0 latex:build (div.tool-panel.tree-view)
     -3:28.8.0 latex:toggle-log (div.tool-panel.tree-view)
     -3:04.0 latex:hide-log (atom-pane.pane.active)
     -2:55.7.0 latex:kill (input.hidden-input)
     -2:52.2.0 latex:clean (input.hidden-input)
     -2:47.9.0 latex:build (input.hidden-input)
  2x -2:03.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.11 
atom-panda-syntax 0.18.0 
git-plus 7.9.3 
language-latex 1.0.0 
latex-autocomplete 1.0.0 
latex-completions 0.3.3 
latexer 0.3.0 
latextools 0.8.5 
pdf-view 0.59.0 
```

**Comment by ashthespy** [comment]
This is an upstream issue (https://github.com/atom/autocomplete-plus/issues/851)  that is something that we are unable to debug/reproduce.

If @schaeferlea can reproduce this, please kindly share more information else I'm going to close this in favour of the main issue thread.
