### ISSUE TITLE
Uncaught Error: not opened

### ISSUE THREAD

**Issue by GarfieldMa** [James-Yu/Atom-LaTeX#95]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.7.12

### Stack Trace

Uncaught Error: not opened

```
At /home/rtma/.atom/packages/atom-latex/node_modules/ws/lib/WebSocket.js:219

Error: not opened
    at WebSocket.send (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:219:16)
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:44:17)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:101:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:47:8)
    at /packages/atom-latex/lib/builder.coffee:63:12
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  3x -1:54.2.0 core:save (input.hidden-input)
  6x -1:35.7.0 core:backspace (input.hidden-input)
  2x -1:34.5.0 core:save (input.hidden-input)
  2x -1:22.7.0 autocomplete-plus:confirm (input.hidden-input)
     -1:19.5.0 core:save (input.hidden-input)
  3x -1:03.0 core:backspace (input.hidden-input)
  2x -1:01.1.0 core:save (input.hidden-input)
     -0:52.5.0 core:backspace (input.hidden-input)
     -0:50.7.0 core:save (input.hidden-input)
  2x -0:33.2.0 core:backspace (input.hidden-input)
  2x -0:19 core:delete (input.hidden-input)
  3x -0:17.1.0 core:move-right (input.hidden-input)
     -0:15.5.0 core:move-down (input.hidden-input)
     -0:15.2.0 core:save (input.hidden-input)
     -0:12.2.0 autocomplete-plus:confirm (input.hidden-input)
  3x -0:12 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-latex 0.7.12 
```

**Comment by ashthespy** [comment]
Could you provide more details as to how you came across the error?

**Comment by GarfieldMa** [comment]
I solved it by install biber on my computer

**Comment by ashthespy** [comment]
Aha!
The new version should throw up a more meaningful error in the future when it can't find the executable. 
Sample on Win10:
```
Command failed: biber main
'biber' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by diegmonti** [comment]
I'm also obtaining the same exception.

1. I open Atom and then I select Build LaTex (everything works as expected);
2. I close the PDF Viewer;
3. I select Build LaTex again or Preview PDF.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.2


### Stack Trace

Uncaught Error: not opened

```
At C:\Users\Diego\.atom\packages\atom-latex\node_modules\ws\lib\WebSocket.js:360

Error: not opened
    at WebSocket.send (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:360:18)
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:43:17)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:120:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:76:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-latex 0.8.2 
```

**Comment by frigatefreedom** [comment]
The same issue as @diegmonti 's.

**Comment by ashthespy** [comment]
I don't seem to be able to reproduce the issue right away, will do some digging.

**Comment by stevechoris** [comment]
I got the same error.
---
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [atom-latex](https://github.com/James-Yu/Atom-LaTeX) package 0.8.2


### Stack Trace

Uncaught Error: not opened

```
At /Users/guanwanxian/.atom/packages/atom-latex/node_modules/ws/lib/WebSocket.js:360

Error: not opened
    at WebSocket.send (/packages/atom-latex/node_modules/ws/lib/WebSocket.js:360:18)
    at Viewer.module.exports.Viewer.refresh (/packages/atom-latex/lib/viewer.coffee:43:17)
    at Builder.module.exports.Builder.postBuild (/packages/atom-latex/lib/builder.coffee:120:21)
    at Builder.module.exports.Builder.buildProcess (/packages/atom-latex/lib/builder.coffee:45:8)
    at /packages/atom-latex/lib/builder.coffee:76:10)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -3:01.3.0 atom-latex:build (input.hidden-input)
     -2:39.7.0 atom-latex:build-here (input.hidden-input)
     -2:03.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dracula-syntax.theme-one-dark-ui)
     -0:59 application:open (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-bracket-highlight 0.3.2 
atom-clock 0.1.15 
atom-copy-on-select 1.4.0 
atom-cscope 1.0.1 
atom-increment 0.3.4 
atom-latex 0.8.2 
atom-runner 2.7.1 
autocomplete-clang 0.11.4 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
clang-format 1.29.0 
dash 1.7.1 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
fancy-bracket-matcher 2.1.0 
file-header 1.13.8 
git-plus undefined 
intentions 1.1.5 
language-latex 1.1.1 
language-markdown 0.25.1 
language-matlab 0.2.1 
latex 0.49.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-ui-default 1.6.10 
markdown-pdf 2.1.0 
markdown-preview-plus 2.4.16 
markdown-scroll-sync 2.1.2 
markdown-table-editor 1.0.1 
markdown-writer 2.7.3 
minimap 4.29.7 
pdf-view 0.61.0 
python-indent 1.1.4 
python-tools 0.6.9 
remote-atom 1.3.11 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.3 
tree-view-git-status 1.4.0 
vim-mode-plus 1.21.0 
```

**Comment by ashthespy** [comment]
Does anyone have any more debugging info I could use to try and recreate this?
1. Tab or Window viewer?
2. Any information in the debug console (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>)

**Comment by diegmonti** [comment]
I can obtain the same behavior with the Tab and the Window viewer.

In the debug console I get the following when I close the viewer the first time:
```
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at TCP.onread (net.js:572)
exports._errnoException @ util.js:1022
onread @ net.js:572
```

Then this when I try to open it again:
```
C:\Users\Diego\.atom\packages\atom-latex\node_modules\ws\lib\WebSocket.js:360 Uncaught Error: not opened
    at WebSocket.send (C:\Users\Diego\.atom\packages\atom-latex\node_modules\ws\lib\WebSocket.js:360)
    at Viewer.module.exports.Viewer.refresh (viewer.coffee:43)
    at Viewer.module.exports.Viewer.openViewer (viewer.coffee:64)
    at HTMLElement.click (panel.js:107)
send @ C:\Users\Diego\.atom\packages\atom-latex\node_modules\ws\lib\WebSocket.js:360
module.exports.Viewer.refresh @ viewer.coffee:43
module.exports.Viewer.openViewer @ viewer.coffee:64
click @ panel.js:107
```

**Comment by nomoon** [comment]
This seems to happen for me when "Do nothing" is set in Preview options.

**Comment by ashthespy** [comment]
Hi all, 
I just figured it out, there is change in the `ws v3.3.3` library which is why I was unable to reproduce on my main workhorse machine.

Anyway, fix coming up tomorrow. In the meantime,
1. Head to  `Settings`→`Atom-LaTeX`→`View Code`
2. Add  the following line in `lib\server.coffee` 
i.e
```
    @ws = new ws.Server server: @http
    @ws.on "connection", (ws) =>
      ws.on "message", (msg) => @latex.viewer.wsHandler(ws, msg)
      ws.on "close", () => @latex.viewer.wsHandler(ws, '{"type":"close"}')

```
becomes
```
    @ws = new ws.Server server: @http
    @ws.on "connection", (ws) =>
      ws.on "message", (msg) => @latex.viewer.wsHandler(ws, msg)
      ws.on "close", () => @latex.viewer.wsHandler(ws, '{"type":"close"}')
      ws.on "error", (msg) => return

```
3. Reload Atom (<kbd>`ctr`</kbd>+<kbd>`shift`</kbd>+<kbd>`F5`</kbd>)
